AllCops:
  Exclude:
    - "Gemfile.lock"
    - "spec/spec_helper.rb"
EndOfLine:
  Enabled: false
Layout/AlignParameters:
<<<<<<< HEAD
<<<<<<< HEAD
  EnforcedStyle: with_fixed_indentation
=======
  EnforcedStyle: with_fixed_indentation  
>>>>>>> 60b38d1... Add gem Rubocop to project
=======
  EnforcedStyle: with_fixed_indentation
>>>>>>> 638f7a3... Create migration for users table
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: true
Layout/IndentationConsistency:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/**/*"
    - "bin/*"
<<<<<<< HEAD
    - "db/*"
=======
>>>>>>> 60b38d1... Add gem Rubocop to project
Metrics/LineLength:
  Max: 80
  Exclude:
    - "config/**/*"
Naming/ClassAndModuleCamelCase:
  Enabled: true
Naming/ConstantName:
  Enabled: true
Style/DefWithParentheses:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
<<<<<<< HEAD
Style/GuardClause:
  Enabled: false
=======
>>>>>>> 60b38d1... Add gem Rubocop to project
Style/IdenticalConditionalBranches:
  Enabled: true
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MixinUsage:
  Exclude:
    - "bin/update"
Style/MutableConstant:
  Exclude:
    - "config/**/*"
Style/NegatedIf:
  Enabled: true
<<<<<<< HEAD
<<<<<<< HEAD
Style/NumericLiterals:
  Exclude:
    - "db/**/*"
=======
>>>>>>> 60b38d1... Add gem Rubocop to project
=======
Style/NumericLiterals:
  Exclude:
    - "db/**/*"
>>>>>>> 638f7a3... Create migration for users table
Style/OneLineConditional:
  Enabled: false
Style/StderrPuts:
  Exclude:
    - "bin/*"
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
