AllCops:
  Exclude:
    - "Gemfile.lock"
    - "spec/spec_helper.rb"
EndOfLine:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: true
Layout/IndentationConsistency:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/**/*"
    - "bin/*"
Metrics/LineLength:
  Max: 80
  Exclude:
    - "spec/**/*"
    - "config/**/*"
    - "db/seeds.rb"
    - "Rakefile"
    - "bin/*"
Naming/ClassAndModuleCamelCase:
  Enabled: true
Naming/ConstantName:
  Enabled: true
Style/DefWithParentheses:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: true
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MixinUsage:
  Exclude:
    - "bin/update"
Style/MutableConstant:
  Exclude:
    - "config/**/*"
Style/NegatedIf:
  Enabled: true
Style/OneLineConditional:
  Enabled: false
Style/StderrPuts:
  Exclude:
    - "bin/*"
Style/StringLiterals:
  EnforcedStyle: double_quotes
