version: 1
jobs:
  build:
    working_directory: ~/BudgetApp
    docker:
            - image: circleci/ruby:2.4.1
            environment:
                environment:
                  PGHOST: localhost
                  PGUSER: BudgetApp
                  RAILS_ENV: test
              - image: postgres:9.6.5
                environment:
                  POSTGRES_USER: BudgetApp
                  POSTGRES_DB: BudgetApp_test
                  POSTGRES_PASSWORD: ""
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install qt5-default

      - checkout

      - run: bundle install --path vendor/bundle

      -restore_cache:
        keys:
          - BudgetApp-gems-{{ checksum "Gemfile.lock" }}
          - BudgetApp-gems-

        -save_cache:
          keys: BudgetApp-gems-{{ checksum "Gemfile.lock" }}
            paths:
              - ./vendor/bundle

      - run: cp .sample.env .env
      - run: bundle exec rubocop
      - run: bundle exec rspec
