version: 2
jobs:
  build:
    working_directory: ~/BudgetApp
    docker:
      - image: circleci/ruby:2.4.1
        environment:
          PGHOST: localhost
          PGUSER: BudgetApp
          RAILS_ENV: test
      - image: postgres:9.6.5
        environment:
          POSTGRES_USER: BudgetApp
          POSTGRES_DB: Budget_App_test
          POSTGRES_PASSWORD: ""

    steps:
      - run: sudo apt-get
      - run: sudo apt-get install qt5-default

      - checkout

      - type: cache-restore
        name: Restore bundle cache
        keys:
          - BudgetApp-gems-{{ checksum "Gemfile.lock" }}
          - BudgetApp-gems-

      - run: bundle install --path vendor/bundle

      - type: cache-save
        name: Store bundle cache
        keys: BudgetApp-gems-{{ checksum "Gemfile.lock" }}
        paths:
          - ./vendor/bundle

      - run: bundle exec rake db:setup
      - run: bundle exec rubocop
      - run: bundle exec rspec
